name: Test and Lint

on:
  push:
  workflow_call:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install packages
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run lint
        run: npm run lint